"use client";import{useEffect,useState}from"react";
function fmt(s){s=Math.max(0,Math.floor(Number(s)||0));return[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map((v,i)=>i?String(v).padStart(2,"0"):String(v)).join(":")}
export default function Home(){const[url,setUrl]=useState("");const[job,setJob]=useState(null);const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);
useEffect(()=>{const id=localStorage.getItem("clipFinderJob");if(id)loadJob(id)},[]);
useEffect(()=>{if(!job||["completed","failed"].includes(job.status))return;const t=setInterval(()=>loadJob(job.id),4000);return()=>clearInterval(t)},[job?.id,job?.status]);
async function loadJob(id){try{const r=await fetch("/api/jobs/"+id,{cache:"no-store"}),d=await r.json();if(r.ok&&d.job){setJob(d.job);setMessage(`${d.job.stage} • ${d.job.progress}%`)}}catch{}}
async function replayV82(){if(!job)return;setLoading(true);setMessage("Iniciando replay V8.2 sem retranscrever a VOD...");try{const r=await fetch("/api/jobs/"+job.id,{method:"PUT"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível iniciar o replay.");await loadJob(job.id)}catch(e){setMessage("Erro: "+e.message)}finally{setLoading(false)}}
async function retomar(){if(!job)return;setLoading(true);setMessage("Retomando do checkpoint...");try{const r=await fetch("/api/jobs/"+job.id,{method:"POST"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível retomar.");await loadJob(job.id)}catch(e){setMessage("Erro: "+e.message)}finally{setLoading(false)}}
async function analisar(e){e.preventDefault();if(!url.trim())return;setLoading(true);setMessage("Criando análise...");try{const r=await fetch("/api/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível criar a análise.");localStorage.setItem("clipFinderJob",d.job.id);setJob(d.job);setMessage(d.workerStarted?"Análise iniciada em segundo plano.":`Job salvo, mas o worker não iniciou: ${d.workerError||"erro desconhecido"}`)}catch(e){setMessage("Erro: "+e.message)}finally{setLoading(false)}}
const candidates=job?.result?.candidates||[];
return <main><section className="hero"><div className="tag">CLIP FINDER • AI • V8.2</div><h1>Encontre cortes.<br/>Poste mais rápido.</h1><p>A análise continua no servidor mesmo se você sair do navegador.</p><form onSubmit={analisar}><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Cole o link do VOD da Kick"/><button disabled={loading}>{loading?"Criando...":"Criar análise"}</button></form>{message&&<div className="status">{message}</div>}{job&&<div className="steps"><b>📡 Análise salva</b><span><strong>Status:</strong> {job.status}</span><span><strong>Etapa:</strong> {job.stage}</span><span><strong>Progresso:</strong> {job.progress}%</span>{job.error&&<span><strong>Erro:</strong> {job.error}</span>}{job.status==="failed"&&String(job.stage||"").includes("V8.2")&&<button type="button" disabled={loading} onClick={replayV82}>{loading?"Retomando replay...":"Retomar replay V8.2"}</button>}{job.status==="failed"&&!String(job.stage||"").includes("V8.2")&&<button type="button" disabled={loading} onClick={retomar}>{loading?"Retomando...":"Retomar do checkpoint"}</button>}{job.status==="completed"&&<button type="button" disabled={loading} onClick={replayV82}>{loading?"Iniciando...":"Reprocessar com V8.2 (sem transcrever)"}</button>}<button type="button" onClick={()=>loadJob(job.id)}>Atualizar agora</button></div>}
{job?.result?.goldenFunnel&&<div className="steps"><b>🔬 Funil dos Golden Moments</b>{job.result.goldenFunnel.goldens?.map((g,i)=><span key={i}><strong>{g.label}</strong><br/>{Object.entries(g.stages||{}).map(([name,x])=><small key={name}>{x.hit?"✅":"❌"} {name}{x.nearest?` • #${x.nearest.rank} • ${fmt(x.nearest.seconds)} • Δ${fmt(x.nearest.distanceSeconds)}`:""}<br/></small>)}</span>)}</div>}{job?.result?.benchmark&&<div className="steps"><b>🧪 Benchmark Brabox</b><span><strong>Descoberta:</strong> {job.result.benchmark.discoveryHits}/{job.result.benchmark.goldens} momentos encontrados</span><span><strong>Top 10:</strong> {job.result.benchmark.top10Hits}/{job.result.benchmark.goldens} momentos encontrados</span>{job.result.benchmark.top10?.map((x,i)=><span key={i}><strong>{x.hit?"✅":"❌"} {x.label}:</strong> {x.nearest?`mais próximo em ${fmt(x.nearest.seconds)} • distância ${fmt(x.nearest.distanceSeconds)} • posição #${x.nearest.rank}`:"sem candidato"}</span>)}</div>}{candidates.length>0&&<div className="results"><h2>Melhores cortes encontrados</h2>{candidates.map((x,i)=><div className="steps" key={i}><b>#{x.rank||i+1} • {x.score}/100 {x.category?` • ${x.category}`:""}</b><span><strong>Trecho:</strong> {fmt(x.startSeconds)} → {fmt(x.endSeconds)}</span><span><strong>Resumo:</strong> {x.summary}</span>{x.evidence&&<span><strong>Fala-chave:</strong> “{x.evidence}”</span>}{x.reason&&<span><strong>Por quê:</strong> {x.reason}</span>}{x.semanticScore!=null&&<span><strong>🧠 Semântico:</strong> {x.semanticScore}/100 • <strong>👁️ Visual:</strong> {x.visualScore||0}/20 • <strong>🎯 Final:</strong> {x.score}/100</span>}{x.visualDescription&&<span><strong>Visual detectado:</strong> {x.visualDescription}</span>}{x.scores&&<details><summary>Ver score detalhado</summary><p>Acontecimento {x.scores.event||0}/20 • Emoção {x.scores.emotion||0}/15 • Humor/conflito/surpresa {x.scores.humor_conflict_surprise||0}/15 • Contexto {x.scores.context||0}/15 • Abertura {x.scores.opening||0}/15 • Comentários {x.scores.comments||0}/10 • Memorável {x.scores.memorable||0}/10</p></details>}<details><summary>Ver transcrição</summary><p>{x.text}</p></details></div>)}</div>}</section></main>}