const KICK_HOSTS=new Set(["kick.com","www.kick.com"]);
function parseVod(raw){try{const u=new URL(raw);if(!KICK_HOSTS.has(u.hostname))return null;const m=u.pathname.match(/^\/([^/]+)\/videos\/([0-9a-fA-F-]{36})\/?$/);if(!m)return null;return{creator:m[1],videoId:m[2],url:u.toString()}}catch{return null}}
function fmt(s){s=Math.max(0,Math.floor(s));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map((v,i)=>i?String(v).padStart(2,"0"):String(v)).join(":")}
function parseMaster(txt,base){const lines=txt.split(/\r?\n/),q=[];for(let i=0;i<lines.length;i++){if(lines[i].startsWith("#EXT-X-STREAM-INF")){const bw=Number((lines[i].match(/BANDWIDTH=(\d+)/)||[])[1]||0);const next=lines.slice(i+1).find(x=>x&&!x.startsWith("#"));if(next){try{q.push({bw,url:new URL(next,base).toString()})}catch{}}}}return q.sort((a,b)=>a.bw-b.bw)}
function durationFromPlaylist(txt){let total=0;for(const m of txt.matchAll(/#EXTINF:([\d.]+)/g))total+=Number(m[1]);return total}
function fallback(duration,count=6){if(!duration)return[];const step=duration/(count+1);return Array.from({length:count},(_,i)=>{const seconds=Math.floor(step*(i+1));return{timestamp:fmt(seconds),seconds}})}
async function transcribe(req,source,start){const audioUrl="https://clip-finder-worker-5xwo.onrender.com/audio-window?"+new URLSearchParams({source:String(source),start:String(Math.max(0,start-35)),duration:"70"}).toString();const origin=new URL(req.url).origin;const r=await fetch(origin+"/api/transcribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({audioUrl}),cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(typeof d?.error==="string"?d.error:JSON.stringify(d?.error||d));return d.text||""}
async function score(text,timestamp,seconds){const prompt=`Você seleciona cortes virais de lives brasileiras. Avalie APENAS a transcrição. Retorne JSON válido: {"score":0-100,"summary":"...","hook":"...","reason":"...","startOffset":-35..0,"endOffset":5..35}. Priorize reação, humor, conflito, história, surpresa e potencial de comentários. Não invente contexto. Timestamp: ${timestamp}. Transcrição: ${text}`;const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-4o-mini",response_format:{type:"json_object"},messages:[{role:"user",content:prompt}],temperature:.2})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Falha ao pontuar");const j=JSON.parse(d.choices?.[0]?.message?.content||"{}");return{score:Math.max(0,Math.min(100,Number(j.score)||0)),summary:j.summary||"Trecho da live",hook:j.hook||"",reason:j.reason||"",startSeconds:Math.max(0,seconds+(Number(j.startOffset)||-25)),endSeconds:Math.max(seconds+5,seconds+(Number(j.endOffset)||25))}}
export const maxDuration=300;
export async function POST(req){let stage="entrada";try{const body=await req.json().catch(()=>({}));const vod=parseVod(body.url||"");if(!vod)return Response.json({ok:false,error:"Cole um link válido de VOD da Kick.",stage},{status:400});
stage="resolver Kick";const wr=await fetch("https://clip-finder-worker-5xwo.onrender.com/resolve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:vod.url}),cache:"no-store"});const raw=await wr.text();let wd={};try{wd=JSON.parse(raw)}catch{throw new Error("Worker retornou resposta inválida.")}if(!wr.ok||!wd?.source)throw new Error(wd?.error||"Worker não retornou fonte do VOD.");
const source=String(wd.source);let duration=Number(wd.duration||0),variant=source;
stage="manifest HLS";const mr=await fetch(source,{cache:"no-store"});if(!mr.ok)throw new Error(`HTTP ${mr.status} no manifest.`);const master=await mr.text();const variants=parseMaster(master,source);variant=variants[0]?.url||source;
stage="playlist HLS";const vr=await fetch(variant,{cache:"no-store"});if(!vr.ok)throw new Error(`HTTP ${vr.status} na playlist.`);const playlist=await vr.text();duration=duration||durationFromPlaylist(playlist);if(!duration)throw new Error("Não consegui calcular a duração.");
stage="scanner de áudio";let probes=[];try{const sr=await fetch("https://clip-finder-worker-5xwo.onrender.com/audio-scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:variant,duration}),cache:"no-store"});const sd=await sr.json();if(sr.ok&&Array.isArray(sd.candidates))probes=sd.candidates.slice(0,10).map(x=>({timestamp:fmt(x.seconds),seconds:Number(x.seconds),audioEnergy:x.energy}))}catch(e){probes=[]}if(!probes.length)probes=fallback(duration);
stage="transcrição e ranking";const results=[];for(const p of probes){try{const text=await transcribe(req,variant,p.seconds);const scored=await score(text,p.timestamp,p.seconds);results.push({...p,...scored,text,start:fmt(scored.startSeconds),end:fmt(scored.endSeconds)})}catch(e){results.push({...p,score:0,summary:"Falha ao analisar trecho",reason:e?.message||String(e),text:""})}}results.sort((a,b)=>b.score-a.score);
return Response.json({ok:true,vod,meta:{title:wd.title||"Kick VOD",durationSeconds:duration,duration:fmt(duration)},candidates:results,status:"scored",message:`Varredura concluída: ${results.length} regiões analisadas e ranqueadas.`});
}catch(e){return Response.json({ok:false,error:`[${stage}] ${e?.message||String(e)}`,stage},{status:502})}}