import{execFile}from"node:child_process";import{promisify}from"node:util";const execFileAsync=promisify(execFile);
import express from"express";const app=express();app.use(express.json({limit:"256kb"}));
const WORKER_SECRET=process.env.WORKER_SECRET||"";
function safeEq(a,b){if(!a||!b||a.length!==b.length)return false;return crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b))}
function requireWorkerAuth(req,res,next){if(!WORKER_SECRET)return res.status(503).json({ok:false,error:"WORKER_SECRET não configurado"});const token=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");if(!safeEq(token,WORKER_SECRET))return res.status(401).json({ok:false,error:"Não autorizado"});next()}
app.get("/health",(_,res)=>res.json({ok:true,service:"clip-finder-worker",version:"V7.0"}));
app.use((req,res,next)=>req.path==="/health"?next():requireWorkerAuth(req,res,next));
function sb(){return{url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY}}
async function patchJob(id,patch){const{url,key}=sb();if(!url||!key)throw new Error("Supabase não configurado no worker");const r=await fetch(url+"/rest/v1/analysis_jobs?id=eq."+encodeURIComponent(id),{method:"PATCH",headers:{apikey:key,Authorization:"Bearer "+key,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Supabase: "+await r.text());return r.json()}

async function resolveVod(url){const m=url.match(/^https:\/\/(?:www\.)?kick\.com\/([^/]+)\/videos\/([0-9a-fA-F-]{36})/);if(!m)throw new Error("URL inválida");const slug=m[1],videoUuid=m[2],session=crypto.randomUUID(),device=crypto.randomUUID();const rr=await fetch(`https://web.kick.com/api/v1/stream/${videoUuid}/playback`,{method:"POST",headers:{accept:"application/json","content-type":"application/json","x-app-platform":"web","user-agent":"Mozilla/5.0"},body:JSON.stringify({video_player:{player:{player_name:"web",player_version:"web_b4f3c23c",player_software:"IVS Player",player_software_version:"1.56.1"}},video_session:{page_type:"video",url_path:`${slug}/videos/${videoUuid}`},user_session:{session_id:session,player_device_id:device}})});const d=await rr.json();const source=d?.playback_url?.vod;if(!rr.ok||!source)throw new Error("Kick não retornou o VOD");return{source,title:d?.video_session?.video_title||"Kick VOD",duration:Number(d?.video_session?.video_duration||0)}}
async function extractAudio(source,start,duration=55){const{stdout}=await execFileAsync("ffmpeg",["-hide_banner","-loglevel","error","-ss",String(Math.max(0,start)),"-i",source,"-t",String(duration),"-vn","-ac","1","-ar","16000","-b:a","48k","-f","mp3","pipe:1"],{timeout:45000,killSignal:"SIGKILL",maxBuffer:8*1024*1024,encoding:"buffer"});return stdout}
async function transcribeAudio(buf){if(!process.env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY não configurada no worker");const form=new FormData();form.append("file",new Blob([buf],{type:"audio/mpeg"}),"clip.mp3");form.append("model","gpt-transcribe");form.append("language","pt");form.append("prompt","Live brasileira de games. Preserve gírias, reações e nomes: Gabepeixe, Coringa, Brabox, BRKK, LOUD.");const rr=await fetch("https://api.openai.com/v1/audio/transcriptions",{method:"POST",headers:{Authorization:"Bearer "+process.env.OPENAI_API_KEY},body:form,signal:AbortSignal.timeout(60000)});const d=await rr.json();if(!rr.ok)throw new Error(d?.error?.message||"Falha na transcrição");return d.text||""}
async function rankTranscript(text,seconds,audioEnergy=0){const prompt=`Você é um editor profissional de cortes de lives brasileiras. Analise SOMENTE a transcrição fornecida; não invente pessoas, ações, risadas, jogadas ou contexto. Queremos acontecimentos que fariam alguém parar no TikTok, não apenas conversa normal.

Retorne JSON: {"category":"😂 Humor|😱 Reação|🔥 Treta|🎮 Jogada|⚽ Futebol|💬 História|🤯 Surpresa|🗣️ Opinião|Outro","evidence":"fala EXATA curta presente na transcrição que prova o momento","summary":"descrição factual curta","reason":"por que vale cortar","scores":{"event":0-20,"emotion":0-15,"humor_conflict_surprise":0-15,"context":0-15,"opening":0-15,"comments":0-10,"memorable":0-10},"suggestedLeadSeconds":0-20}. Seja rigoroso: conversa cotidiana sem payoff deve pontuar baixo. Não crie gancho publicitário. Se não houver evidência clara, evidence="". Categoria também deve ser factual: use 🔥 Treta somente quando houver discussão, provocação, conflito ou controvérsia explícita; celebração/frustração é 😱 Reação; assunto ou comemoração de futebol sem conflito é ⚽ Futebol.

TRANSCRIÇÃO:
${text}`;const rr=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:"Bearer "+process.env.OPENAI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-4o-mini",response_format:{type:"json_object"},messages:[{role:"user",content:prompt}],temperature:.1}),signal:AbortSignal.timeout(45000)});const d=await rr.json();if(!rr.ok)throw new Error(d?.error?.message||"Falha no ranking");const j=JSON.parse(d.choices?.[0]?.message?.content||"{}"),s=j.scores||{},semantic=["event","emotion","humor_conflict_surprise","context","opening","comments","memorable"].reduce((n,k)=>n+(Number(s[k])||0),0),energyBonus=Math.min(5,Math.max(0,Number(audioEnergy)||0)/20),score=Math.round(Math.min(100,semantic*.95+energyBonus));return{seconds,score,category:j.category||"Outro",evidence:j.evidence||"",summary:j.summary||"Trecho da live",reason:j.reason||"",scores:s,suggestedLeadSeconds:Math.max(0,Math.min(20,Number(j.suggestedLeadSeconds)||0)),text}}
async function extractFrame(source,t){const{stdout}=await execFileAsync("ffmpeg",["-hide_banner","-loglevel","error","-ss",String(Math.max(0,t)),"-i",source,"-frames:v","1","-vf","scale=640:-2","-q:v","5","-f","image2pipe","-vcodec","mjpeg","pipe:1"],{timeout:35000,killSignal:"SIGKILL",maxBuffer:4*1024*1024,encoding:"buffer"});return stdout}
async function visualScore(v,p){try{const times=[p.seconds-12,p.seconds,p.seconds+12].map(x=>Math.max(0,x)),imgs=[];for(const t of times){const b=await deadline(extractFrame(v.source,t),40000,"Frame");imgs.push("data:image/jpeg;base64,"+b.toString("base64"))}const content=[{type:"text",text:"Analise estes 3 frames sequenciais de uma live brasileira, antes/durante/depois de um momento candidato. Não identifique pessoas. Compare os 3 frames como uma SEQUÊNCIA temporal. Pontue somente MUDANÇA observável que fortaleça um corte: expressão/postura mudando claramente, pessoa levantando/recuando, interação física, comemoração, susto, confusão, ação inesperada ou transformação relevante entre antes/durante/depois. Cenário bonito/colorido, máscaras/roupas, iluminação, presença de pessoas, câmera diferente ou imagem interessante SEM mudança temporal valem 0-3. Cena estática vale 0-2. Não invente áudio/contexto. Retorne JSON {visualScore:0-20, visualEvent:true|false, description:'descreva a mudança temporal observada; se não houver, diga cena estática/sem reação relevante'}."},...imgs.map(image_url=>({type:"image_url",image_url:{url:image_url,detail:"low"}}))];const rr=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{Authorization:"Bearer "+process.env.OPENAI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-4o-mini",response_format:{type:"json_object"},messages:[{role:"user",content}],temperature:.1}),signal:AbortSignal.timeout(45000)});const d=await rr.json();if(!rr.ok)throw new Error(d?.error?.message||"Falha visual");const j=JSON.parse(d.choices?.[0]?.message?.content||"{}");return{visualScore:Math.max(0,Math.min(20,Number(j.visualScore)||0)),visualEvent:Boolean(j.visualEvent),visualDescription:j.description||""}}catch(e){return{visualScore:0,visualEvent:false,visualDescription:"Análise visual indisponível: "+e.message}}}
async function audioProbe(source,t){try{const e=await execFileAsync("ffmpeg",["-hide_banner","-ss",String(Math.max(0,t)),"-i",source,"-t","9","-vn","-af","volumedetect","-f","null","-"],{timeout:30000,maxBuffer:1024*1024});const s=String(e.stderr||""),mean=Number((s.match(/mean_volume:\s*(-?[\d.]+) dB/)||[])[1]),peak=Number((s.match(/max_volume:\s*(-?[\d.]+) dB/)||[])[1]);if(!Number.isFinite(mean)||!Number.isFinite(peak))return null;return{seconds:t,meanDb:mean,peakDb:peak,energy:Math.max(0,mean+45)*1.6+Math.max(0,peak+18)*2.4}}catch{return null}}
async function discoverMoments(id,v){const samples=72,step=v.duration/(samples+1),probes=[];for(let i=1;i<=samples;i++){await patchJob(id,{status:"scanning",progress:10+Math.round(i/samples*20),stage:`V7.0 • mapa amplo ${i} de ${samples}`,result:{title:v.title,durationSeconds:v.duration,scan:{index:i-1,samples,probes}}});const p=await deadline(audioProbe(v.source,Math.floor(step*i)),35000,"Sondagem");if(p)probes.push({...p,index:i});await patchJob(id,{status:"scanning",progress:10+Math.round(i/samples*20),stage:`Checkpoint do mapa ${i}/${samples}`,result:{title:v.title,durationSeconds:v.duration,scan:{index:i,samples,probes}}})}
if(!probes.length)return Array.from({length:10},(_,i)=>({seconds:Math.floor(v.duration*(i+1)/11),energy:0,change:0,fallback:true}));
const es=probes.map(x=>x.energy).sort((a,b)=>a-b),median=es[Math.floor(es.length/2)]||0;for(let i=0;i<probes.length;i++){const prev=probes[i-1]?.energy??median,next=probes[i+1]?.energy??median;probes[i].change=Math.max(0,probes[i].energy-prev,probes[i].energy-next);probes[i].interest=(probes[i].energy-median)*.4+probes[i].change*1.4}
probes.sort((a,b)=>b.interest-a.interest);const seeds=[];for(const p of probes){if(seeds.every(x=>Math.abs(x.seconds-p.seconds)>150))seeds.push(p);if(seeds.length>=10)break}return seeds}
async function refineSeed(v,s){const local=[];for(const off of[-30,0,30]){const t=Math.max(5,Math.min(v.duration-10,s.seconds+off)),p=await audioProbe(v.source,t);if(p)local.push(p)}if(!local.length)return s;local.sort((x,y)=>y.energy-x.energy);const peak=local[0],base=local.map(x=>x.energy).sort((x,y)=>x-y)[Math.floor(local.length/2)]||0;return{...peak,change:Math.max(0,peak.energy-base),interest:(s.interest||0)+(peak.energy-base)*1.5,zoneCenter:s.seconds}}
async function refineQueue(id,url,v,seeds,index=0,refined=[]){if(index>=seeds.length){refined.sort((a,b)=>b.interest-a.interest);const moments=refined.slice(0,10);await patchJob(id,{status:"transcribing",progress:46,stage:"Refinamento concluído • iniciando candidatos",result:{title:v.title,durationSeconds:v.duration,refinedZones:refined,partialCandidates:[]}});return setTimeout(()=>processCandidateQueue(id,url,v,moments,0,[]),250)}
await patchJob(id,{status:"scanning",progress:31+Math.round(index/seeds.length*14),stage:`V7.0 • refinando zona ${index+1} de ${seeds.length}`,result:{title:v.title,durationSeconds:v.duration,seeds,refinedZones:refined,refineIndex:index}});
let item;try{item=await deadline(refineSeed(v,seeds[index]),70000,"Refinamento")}catch{item=seeds[index]}refined=[...refined,item];await patchJob(id,{status:"scanning",progress:31+Math.round((index+1)/seeds.length*14),stage:`Checkpoint de zona ${index+1}/${seeds.length}`,result:{title:v.title,durationSeconds:v.duration,seeds,refinedZones:refined,refineIndex:index+1}});
setTimeout(()=>refineQueue(id,url,v,seeds,index+1,refined).catch(async e=>patchJob(id,{status:"failed",stage:"Refinamento interrompido",error:e.message}).catch(()=>{})),250)}
function deadline(p,ms,label){let t;return Promise.race([p,new Promise((_,rej)=>{t=setTimeout(()=>rej(new Error(label+" excedeu "+Math.round(ms/1000)+"s")),ms)})]).finally(()=>clearTimeout(t))}
async function analyzeCandidate(v,p){let last;for(let attempt=1;attempt<=2;attempt++){try{return await deadline((async()=>{const audio=await extractAudio(v.source,Math.max(0,p.seconds-35),70),text=await transcribeAudio(audio),ranked=await rankTranscript(text,p.seconds,p.energy),visual=await visualScore(v,p);const visualDelta=visual.visualEvent?Math.round((visual.visualScore-10)*0.6):Math.min(0,Math.round((visual.visualScore-6)*0.35));const fused=Math.max(0,Math.min(100,ranked.score+visualDelta));return{...ranked,...visual,semanticScore:ranked.score,score:fused,audioEnergy:Math.round(p.energy*10)/10,audioChange:Math.round((p.change||0)*10)/10,interest:Math.round((p.interest||0)*10)/10,attempts:attempt}})(),115000,"Candidato")}catch(e){last=e;if(attempt<2){try{const fresh=await deadline(resolveVod(v.url),20000,"Renovação do VOD");v.source=fresh.source}catch{}await new Promise(r=>setTimeout(r,1000))}}}throw last||new Error("Falha no candidato")}
async function processJob(id,url){try{await patchJob(id,{status:"resolving",progress:5,stage:"Resolvendo VOD",error:null});const v=await resolveVod(url);v.url=url;if(!v.duration)throw new Error("Duração do VOD indisponível");await patchJob(id,{status:"scanning",progress:10,stage:"V7.0 • criando mapa de interesse",result:{title:v.title,durationSeconds:v.duration}});const seeds=await discoverMoments(id,v);if(!seeds.length)throw new Error("Scanner não encontrou regiões analisáveis");await patchJob(id,{status:"scanning",progress:31,stage:"V7.0 • refinamento persistente iniciado",result:{title:v.title,durationSeconds:v.duration,seeds,refinedZones:[],refineIndex:0}});setImmediate(()=>refineQueue(id,url,v,seeds,0,[]))}catch(e){await patchJob(id,{status:"failed",progress:0,stage:"Falha no processamento",error:e.message}).catch(()=>{})}}
async function processCandidateQueue(id,url,v,moments,index,out){if(index>=moments.length){out.sort((a,b)=>b.score-a.score);const candidates=out.filter(x=>x.score>=50&&(x.semanticScore>=45||x.visualScore>=10)).slice(0,10).map((x,i)=>({...x,rank:i+1,startSeconds:Math.max(0,x.seconds-35+(x.suggestedLeadSeconds||0)),endSeconds:x.seconds+35}));return patchJob(id,{status:"completed",progress:100,stage:"Análise concluída",result:{title:v.title,durationSeconds:v.duration,scanner:{version:"V7.0",samples:72,shortlisted:moments.length,method:"checkpointed-coarse-refine-candidate"},candidates}})}
const p=moments[index],progress=46+Math.round(index/moments.length*44);await patchJob(id,{status:"transcribing",progress,stage:`Processando candidato ${index+1} de ${moments.length}`,result:{title:v.title,durationSeconds:v.duration,queue: moments.map((x,i)=>({index:i,status:i<index?"done":i===index?"processing":"queued",seconds:x.seconds})),partialCandidates:out}});
try{const candidate=await analyzeCandidate(v,p);out=[...out,candidate]}catch(e){out=[...out,{seconds:p.seconds,score:0,summary:"Falha neste trecho",reason:e.message,text:""}]}
await patchJob(id,{status:"transcribing",progress:46+Math.round((index+1)/moments.length*44),stage:`Checkpoint ${index+1}/${moments.length} salvo`,result:{title:v.title,durationSeconds:v.duration,queue:moments.map((x,i)=>({index:i,status:i<=index?"done":"queued",seconds:x.seconds})),partialCandidates:out}});
setTimeout(async()=>{try{const base=`http://127.0.0.1:${process.env.PORT||10000}`;const rr=await fetch(base+"/jobs/step",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,url,moments,index:index+1,out}),signal:AbortSignal.timeout(5000)});if(!rr.ok)throw new Error("Falha ao iniciar próxima etapa")}catch(e){await patchJob(id,{status:"failed",stage:"Falha ao agendar próxima etapa",error:e.message}).catch(()=>{})}},250)}
app.post("/jobs/start",async(req,res)=>{const id=String(req.body?.id||""),url=String(req.body?.url||"");if(!/^[0-9a-f-]{36}$/i.test(id)||!url)return res.status(400).json({ok:false,error:"Job inválido"});res.status(202).json({ok:true,id});setImmediate(()=>processJob(id,url))});
app.post("/jobs/step",async(req,res)=>{const id=String(req.body?.id||""),url=String(req.body?.url||""),moments=Array.isArray(req.body?.moments)?req.body.moments:[],index=Number(req.body?.index||0),out=Array.isArray(req.body?.out)?req.body.out:[];if(!/^[0-9a-f-]{36}$/i.test(id)||!url||!moments.length)return res.status(400).json({ok:false,error:"Etapa inválida"});res.status(202).json({ok:true,id,index});setImmediate(async()=>{try{const v=await resolveVod(url);v.url=url;await processCandidateQueue(id,url,v,moments,index,out)}catch(e){await patchJob(id,{status:"failed",stage:"Etapa independente falhou",error:e.message}).catch(()=>{})}})});

app.listen(process.env.PORT||10000,"0.0.0.0");