import express from"express";import{chromium}from"playwright";const app=express();app.use(express.json());app.get("/",(_,r)=>r.json({ok:true,service:"clip-finder-kick-worker"}));
app.post("/resolve",async(req,res)=>{const url=req.body?.url;if(!/^https:\/\/(www\.)?kick\.com\/[^/]+\/videos\/[A-Za-z0-9-]+/.test(url||""))return res.status(400).json({ok:false,error:"URL inválida"});let browser;try{browser=await chromium.launch({headless:true,args:["--no-sandbox","--disable-dev-shm-usage"]});const page=await browser.newPage({userAgent:"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1"});let source=null;const seen=[];
page.on("request",r=>{const u=r.url();if(/m3u8|playlist|master/i.test(u)){seen.push(u);if(u.includes(".m3u8"))source=u}});
page.on("response",async r=>{const u=r.url(),ct=r.headers()["content-type"]||"";if(source)return;if(/mpegurl|m3u8/i.test(ct)||u.includes(".m3u8"))source=u;});
await page.goto(url,{waitUntil:"domcontentloaded",timeout:90000});await page.waitForTimeout(5000);
for(const sel of["video","button[aria-label*=play i]","button:has-text('Play')"]){try{await page.locator(sel).first().click({timeout:2500});break}catch{}}
await page.waitForTimeout(12000);const title=await page.title();
if(!source){const data=await page.evaluate(()=>{const out=[];for(const s of document.scripts){const t=s.textContent||"";for(const m of t.matchAll(/https?:[^"'\\s<>]+(?:m3u8|playlist)[^"'\\s<>]*/gi))out.push(m[0])}const v=document.querySelector("video");if(v?.src)out.push(v.src);return out});source=data.find(x=>x.includes(".m3u8"))||data[0]||null}
if(!source)return res.status(404).json({ok:false,error:"Playlist do VOD não encontrada",debug:{title,url:page.url(),candidates:seen.slice(-10)}});
res.json({ok:true,source,title})}catch(e){res.status(500).json({ok:false,error:e.message})}finally{if(browser)await browser.close()}});
app.post("/clips",async(req,res)=>{const creator=String(req.body?.creator||"").replace(/[^a-zA-Z0-9_-]/g,"");if(!creator)return res.status(400).json({ok:false,error:"Canal ausente"});try{const r=await fetch(`https://kick.com/api/v2/channels/${creator}/clips?sort=view&time=week`,{headers:{"User-Agent":"Mozilla/5.0","Accept":"application/json"}});if(!r.ok)throw new Error("Kick não liberou os clips do canal");const d=await r.json();const list=Array.isArray(d)?d:(d?.clips||d?.data||[]);const clips=list.slice(0,30).map(x=>({id:x.id||x.clip_id,title:x.title||"",views:x.views||x.view_count||0,createdAt:x.created_at||null,thumbnail:x.thumbnail_url||x.thumbnail||null,url:x.clip_url||x.url||(x.id?`https://kick.com/${creator}?clip=${x.id}`:null),duration:x.duration||null}));res.json({ok:true,creator,clips})}catch(e){res.status(502).json({ok:false,error:e.message})}});
app.listen(process.env.PORT||10000,"0.0.0.0");